- name: Coaching
  url: coaching
  icon: 
  description: "Tillidsskabende, troværdig og utrolig dedikeret life- og businesscoach, der hjælper dig med at nå dine mål. Jeg er med dig hele vejen."
  delay: .0s
- name: Massage
  url: massage
  icon: 
  description: "Erfaren og kompetent massør tilbyder forskellige former for massage. Herunder også muskeltests, tapening med bl.a. kinesiotape og sportstape, triggerpunktsterapi samt sportsakupunktur."
  delay: .1s
